#!/bin/sh

case "$1" in
    start)
        echo "Load module misc-modules and scull"
        /usr/bin/module_load faulty
        /usr/bin/scull_load
        modprobe hello
        ;;
    stop)
        echo "Stop scull and misc-modules"
        /usr/bin/module_unload faulty
        /usr/bin/scull_unload
        rmmod hello
        ;;
      *)
        echo "Usage: $0 {start|stop}"
        exit 1
esac

exit 0
